from pydantic import BaseModel, Field


class AgentRequest(BaseModel):
    """
    Request model for the Multi-Agent System.
    """

    message: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="User input for the Multi-Agent System",
        examples=["Compare Python and Java for backend development."],
    )


class AgentResponse(BaseModel):
    """
    Final response returned by the Multi-Agent System.
    """

    success: bool = Field(
        ...,
        description="Whether the workflow completed successfully",
    )

    session_id: str = Field(
        ...,
        description="Current chat session ID",
    )

    response: str = Field(
        ...,
        description="Final response generated by the AI",
    )


class PlannerResponse(BaseModel):
    """
    Planner output.
    """

    goal: str
    agents: list[str]


class ResearchResponse(BaseModel):
    """
    Researcher output.
    """

    research: str


class AnalysisResponse(BaseModel):
    """
    Analyzer output.
    """

    analysis: str


class WriterResponse(BaseModel):
    """
    Writer output.
    """

    response: str